# Generated by Django 4.2 on 2026-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('your_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('issue_category', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='ticket_images/')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('company', models.CharField(choices=[('CEL', 'CEL'), ('CMPL', 'CMPL')], max_length=4)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
